### ISSUE TITLE
Create base for Rails app

### ISSUE THREAD

**Issue by HeroicEric** [LaunchAcademy/celebrity_mugshot_review#9]
- [x] Configure database
- [x] Setup testing tools

**Comment by hannah** [comment]
great idea!

**Comment by townie** [comment]
Updated check latest version

**Comment by HeroicEric** [comment]
@LaunchAcademy/celebrity-mugshot-reviews Don't merge directly into master, create a pull request for the team to review before it's merged in.

You should reference the issue that your pull request is fixing either in a commit message or in the pull request so that the issue is closed when the pull request is merged in.

https://help.github.com/articles/closing-issues-via-commit-messages
